# Build the native Android mobile extension from a project path that may
# contain non-ASCII characters. Android's CMake/JNI task can encode such
# paths incorrectly, so this helper stages the Flutter sources in an ASCII
# directory and copies the APK back to the project build directory.

[CmdletBinding()]
param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Debug",
    [switch]$Core,
    [switch]$RunNativeTests,
    [string]$ApiBaseUrl = ""
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$previousLocation = Get-Location
$stagingRoot = $null

function Copy-StageDirectory {
    param(
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Destination
    )
    if (-not (Test-Path -LiteralPath $Source)) {
        throw "Required project directory is missing: $Source"
    }
    & robocopy $Source $Destination /E /NFL /NDL /NJH /NJS /NP | Out-Null
    if ($LASTEXITCODE -gt 7) {
        throw "Unable to stage $Source (robocopy $LASTEXITCODE)."
    }
}

try {
    Set-Location $projectRoot
    if ($Core) {
        & (Join-Path $projectRoot 'scripts/Test-CoreSource.ps1') -ProjectRoot $projectRoot
    } elseif (Test-Path -LiteralPath (Join-Path $projectRoot 'core-build.json')) {
        throw 'This is a core source export. Build it with -Core.'
    }
    $buildRoot = $projectRoot
    if ($projectRoot -match '[^\x00-\x7F]') {
        $stagingBase = [System.IO.Path]::GetFullPath(
            [Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
        ).TrimEnd('\')
        $stagingRoot = Join-Path $stagingBase "sohun_android_$PID"
        $resolvedStagingRoot = [System.IO.Path]::GetFullPath($stagingRoot)
        if (-not $resolvedStagingRoot.StartsWith("$stagingBase\sohun_android_", [System.StringComparison]::OrdinalIgnoreCase)) {
            throw "Refusing to create an unexpected Android staging directory."
        }
        if (Test-Path -LiteralPath $resolvedStagingRoot) {
            Remove-Item -LiteralPath $resolvedStagingRoot -Recurse -Force
        }
        New-Item -ItemType Directory -Force -Path $resolvedStagingRoot | Out-Null

        Copy-StageDirectory (Join-Path $projectRoot "android") (Join-Path $resolvedStagingRoot "android")
        foreach ($generatedDir in @("android\build", "android\.gradle", "android\.kotlin")) {
            $stagedGeneratedDir = Join-Path $resolvedStagingRoot $generatedDir
            if (Test-Path -LiteralPath $stagedGeneratedDir) {
                Remove-Item -LiteralPath $stagedGeneratedDir -Recurse -Force
            }
        }
        Copy-StageDirectory (Join-Path $projectRoot "assets") (Join-Path $resolvedStagingRoot "assets")
        Copy-StageDirectory (Join-Path $projectRoot "lib") (Join-Path $resolvedStagingRoot "lib")
        # The sqlite3 Dart native-assets hook caches verified Android
        # libraries under .dart_tool.  Keep that small, content-addressed
        # cache when staging a non-ASCII project path so an Android build does
        # not depend on a transient GitHub download.  (The rest of .dart_tool
        # is intentionally regenerated by flutter pub get.)
        $sqliteHookSource = Join-Path $projectRoot ".dart_tool\hooks_runner\shared\sqlite3\build"
        if (Test-Path -LiteralPath $sqliteHookSource) {
            Copy-StageDirectory $sqliteHookSource (Join-Path $resolvedStagingRoot ".dart_tool\hooks_runner\shared\sqlite3\build")
            Write-Host "[android] Seeded verified sqlite3 native-assets cache"
        }
        foreach ($fileName in @("pubspec.yaml", "pubspec.lock", "analysis_options.yaml", ".metadata")) {
            $sourceFile = Join-Path $projectRoot $fileName
            if (Test-Path -LiteralPath $sourceFile) {
                Copy-Item -LiteralPath $sourceFile -Destination (Join-Path $resolvedStagingRoot $fileName) -Force
            }
        }
        $buildRoot = $resolvedStagingRoot
        Write-Host "[android] Staged project at $buildRoot"
    }

    Set-Location $buildRoot
    flutter pub get
    if ($LASTEXITCODE -ne 0) { throw "flutter pub get failed." }

    if ($RunNativeTests) {
        Push-Location (Join-Path $buildRoot 'android')
        try {
            & .\gradlew.bat :app:testDebugUnitTest --no-daemon
            if ($LASTEXITCODE -ne 0) {
                throw "Android native unit tests failed (exit $LASTEXITCODE)."
            }
        } finally {
            Pop-Location
        }
    }

    $buildArgs = @("build", "apk", "--$($Configuration.ToLowerInvariant())", "-t", "lib/main_mobile.dart")
    if ($Core) { $buildArgs += '--dart-define=SOHUN_CORE_BUILD=true' }
    if (-not [string]::IsNullOrWhiteSpace($ApiBaseUrl)) {
        $buildArgs += "--dart-define=APP_API_BASE_URL=$($ApiBaseUrl.Trim().TrimEnd('/'))"
    }
    & flutter @buildArgs
    if ($LASTEXITCODE -ne 0) {
        throw "Flutter Android build failed (exit $LASTEXITCODE)."
    }

    $apkName = if ($Configuration -eq "Release") { "app-release.apk" } else { "app-debug.apk" }
    $builtApk = Join-Path $buildRoot "build\app\outputs\flutter-apk\$apkName"
    if (-not (Test-Path -LiteralPath $builtApk)) {
        throw "Expected APK was not produced: $builtApk"
    }
    if ($Core) { & (Join-Path $projectRoot 'scripts/Test-CoreBundle.ps1') -BundlePath $builtApk }
    $projectApk = Join-Path $projectRoot "build\app\outputs\flutter-apk\$apkName"
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $projectApk) | Out-Null
    if (-not [string]::Equals(
        [IO.Path]::GetFullPath($builtApk),
        [IO.Path]::GetFullPath($projectApk),
        [StringComparison]::OrdinalIgnoreCase
    )) {
        Copy-Item -LiteralPath $builtApk -Destination $projectApk -Force
    }
    Write-Host "[android] APK: $projectApk" -ForegroundColor Green
}
finally {
    Set-Location $previousLocation
    if ($null -ne $stagingRoot -and (Test-Path -LiteralPath $stagingRoot)) {
        $stagingBase = [System.IO.Path]::GetFullPath(
            [Environment]::GetFolderPath([Environment+SpecialFolder]::LocalApplicationData)
        ).TrimEnd('\')
        $resolvedStagingRoot = [System.IO.Path]::GetFullPath($stagingRoot)
        if ($resolvedStagingRoot.StartsWith("$stagingBase\sohun_android_", [System.StringComparison]::OrdinalIgnoreCase)) {
            Remove-Item -LiteralPath $resolvedStagingRoot -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}
