import { productStyles } from './product_styles.js';

export const marketingStyles = productStyles + `
  .utility-page{display:flex;flex-direction:column;min-height:100vh;isolation:isolate}.utility-page .site-footer{margin-top:auto}.access-main{display:grid;grid-template-columns:1.05fr .95fr;gap:90px;align-items:center;width:min(1060px,calc(100% - 64px));margin:0 auto;padding:95px 0 100px;flex:1}.access-copy h1{font-size:clamp(40px,4.1vw,57px);line-height:1.3;letter-spacing:-1.8px}.access-copy h1 span{display:block;color:var(--green-dark)}.access-copy>p{font-size:15px;color:var(--muted);margin-top:22px;line-height:1.9;max-width:415px}.access-features{display:grid;gap:22px;margin-top:37px}.access-feature{display:flex;align-items:center;gap:14px}.access-feature>.icon{width:22px;height:22px;color:var(--green-dark)}.access-feature strong{display:block;font-size:13px;font-weight:550}.access-feature p{font-size:11px;color:var(--muted);margin-top:3px}.access-panel{position:relative;padding:36px;background:rgba(255,255,255,.7);border:1px solid #fff;border-radius:24px;box-shadow:0 24px 60px -32px rgba(32,74,49,.25),inset 0 1px 0 #fff}.access-panel::before{content:"";position:absolute;z-index:-1;inset:-60px 0;background:radial-gradient(ellipse,rgba(0,180,42,.06),transparent 65%);pointer-events:none}.access-lock{display:grid;place-items:center;width:43px;height:43px;background:var(--green-soft);border:1px solid #fff;border-radius:13px;color:var(--green-dark);margin-bottom:23px}.access-panel h2{font-size:23px;line-height:1.4}.access-panel>p{font-size:12px;color:var(--muted);margin:10px 0 23px}.field{margin-top:20px}.field label{display:block;font-size:12px;font-weight:550;margin-bottom:9px}.field input{width:100%;height:48px;border:1px solid rgba(35,69,49,.14);border-radius:11px;background:rgba(255,255,255,.65);padding:0 14px;outline:none;font-size:13px;color:var(--text)}.field input::placeholder{color:#7b8c82}.field input:focus{border-color:var(--green-dark);box-shadow:0 0 0 3px rgba(0,180,42,.09)}.access-submit{width:100%;margin-top:25px;min-height:49px;cursor:pointer}.access-help{border-top:1px solid var(--line);padding-top:19px;margin:24px 0 0!important;line-height:1.8;font-size:11px!important}.access-help a{color:var(--green-dark)}.form-error{background:var(--danger-soft);border:1px solid #ffccc7;border-radius:11px;padding:12px 14px;font-size:12px;color:var(--danger);line-height:1.7;margin:18px 0}
  .message-main{flex:1;display:grid;place-items:center;width:min(660px,calc(100% - 40px));margin:0 auto;padding:82px 0}.message-panel{width:100%;text-align:center;padding:50px 40px}.message-symbol{width:62px;height:62px;display:grid;place-items:center;margin:0 auto 27px;background:var(--green-soft);color:var(--green-dark);border:1px solid #fff;border-radius:18px}.message-symbol .icon{width:29px;height:29px}.message-panel h1{font-size:32px;line-height:1.45;letter-spacing:-.8px}.message-panel>p{font-size:14px;line-height:1.9;color:var(--muted);max-width:440px;margin:19px auto 28px}.message-actions{display:flex;justify-content:center;gap:12px;flex-wrap:wrap}.message-caption{margin-top:25px;font-size:11px;color:var(--faint)}
  @media(max-width:1000px){.access-main{gap:48px}}
  @media(max-width:800px){.access-main{grid-template-columns:1fr;gap:40px;max-width:520px;width:calc(100% - 40px);padding:59px 0 65px}.access-copy>p{max-width:none}.access-features{gap:17px;margin-top:26px}.access-copy h1 span{display:inline}}
  @media(max-width:560px){.access-copy h1{font-size:38px}.access-panel{padding:27px 24px;border-radius:16px}.access-copy>p{font-size:14px}.message-main{padding:55px 0}.message-panel{padding:37px 24px}.message-panel h1{font-size:26px}.message-panel>p{font-size:13px}.message-actions{flex-direction:column}.message-actions a{width:100%}}
`;
